language: php

php:
- 7.2
- 7.3
- nightly

services:
- mysql

sudo: false

install:
- mysql -u root -e 'create database streber;'
- composer self-update
- composer install --no-interaction
- cp .env.travis .env
- ./bin/console doctrine:migrations:migrate -n

script:
- vendor/bin/phpcs  --standard=phpcs.xml -n
- vendor/bin/phpstan analyse