strava:
  image: webdevops/php-nginx:7.2
  ports:
    - 8085:80
  environment:
    - WEB_DOCUMENT_ROOT=/app/public/
  volumes:
    - ./:/app
  links:
    - mysql

mysql:
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: ThisIsFarTooSimple
    MYSQL_DATABASE: strava